//import lazy

import * as image from './images'

type CurriculumData = {
  title: string
  contents: string[]
}[]

type ICourseData = {
  id: string
  imgUrl: string
  videoUrl?: string
  curriculum?: CurriculumData
}

export const courseData: ICourseData[] = [
  {
    id: '7283',
    imgUrl: image.comercioExt,
    videoUrl: 'a_Qcva1BJIo',
    curriculum: [
      {
        title: 'Auxiliar Administrativo – CBO 4110-05',
        contents: [
          'Introdução a Administração',
          'Empreendedorismo',
          'Introdução ao Empreendedorismo',
          'Teorias Aplicadas na Administração',
          'Matemática Financeira',
          'Introdução a Matemática Financeira',
          'Gestão da Qualidade Total',
          'Modelos de Gestão',
          'Organização, Sistemas e Métodos',
          'Processos Gerenciais',
        ],
      },
      {
        title: 'Auxiliar de Agente de Comércio Exterior – CBO 3421-05',
        contents: [
          'Tributos Aplicados ao Comércio Exterior',
          'Planejamento e Viabilidade das Operações de Exportação e Importação',
          'Identificação e Análise de Oportunidades Nacionais e Internacionais',
          'Sistemática de Comércio Exterior',
          'Logística Internacional',
          'Logística Aduaneira',
          'Projeto Prático em Comércio Exterior I',
        ],
      },
      {
        title: 'Gerais',
        contents: [
          'Gestão da Distribuição Física',
          'Gestão do Despacho Aduaneiro',
          'Normas Administrativas e Aduaneiras',
          'Sistemática das Operações de Logística Internacional',
          'Projeto Prático em Comércio Exterior II',
        ],
      },
      {
        title: 'Trabalho de Conclusão de Curso',
        contents: ['Trabalho de Conclusão de Curso'],
      },
    ],
  },
  {
    id: '26',
    imgUrl: image.adm,
    videoUrl: 'IqCc-0gUTLg',
    curriculum: [
      {
        title: 'AUXILIAR ADMINISTRATIVO – CBO 4110-05',
        contents: [
          'Introdução a Administração - sg',
          'Empreendedorismo - sg',
          'Introdução ao Empreendedorismo - rd',
          'Teorias Aplicadas na Administração - sg',
          'Matemática Financeira - sg',
          'Introdução a Matemática Financeira - rd',
          'Gestão da Qualidade Total - sg',
          'Modelos de Gestão - sg',
          'Organização, Sistemas e Métodos - sg',
          'Processos Gerenciais - sg',
        ],
      },
      {
        title: 'AUXILIAR DE ESCRITÓRIO – CBO 4110-05',
        contents: [
          'Teoria geral da empresa - sg',
          'Teoria Geral da Administração I - sg',
          'Administração de Marketing I - sg',
          'Administração da Produção - sg',
          'Administração de Produtos e Serviços - sg',
          'Administração de Vendas - sg',
        ],
      },
      {
        title: 'AUXILIAR CONTÁBIL – CBO – 4131-10',
        contents: [
          'Administração Financeira - sg',
          'Fundamentos da Contabilidade - sg',
          'Contabilidade para não Contadores - rd',
          'Plano de Negócios -sg',
          'Fundamentos da Economia - sg',
        ],
      },
      {
        title: 'AUXILIAR DE RECURSOS HUMANOS – CBO 4110-05',
        contents: [
          'Administração de Pessoal  - sg',
          'Planejamento estratégico I - sg',
          'Custos e Formação do Preço de Venda - rd',
          'Sistemas de produção I - sg',
          'Projeto Pratico em Administração I',
        ],
      },
      {
        title: 'AUXILIAR DE ESTOQUE – CBO 4141-25',
        contents: [
          'Teoria Geral da Administração II - sg',
          'Comercio Eletrônico - sg',
          'Administração de micro e pequenas empresas - sg',
          'Sistemas de produção II - sg',
          'Gestão de Armazenamento, Estoque e Distribuição - sg',
          'Administração de Marketing II - sg',
          'Planejamento estratégico II - sg',
        ],
      },
      {
        title: 'ATENDENTE DE INFORMAÇÕES – CBO – 4223-15',
        contents: [
          'Planejamento Estratégico - rd',
          'Gerenciamento de Riscos - sg',
          'Gestão de Vendas e Negociação - sg',
          'Técnicas de Negociação - rd',
          'Gestão do desempenho organizacional - sg',
          'Sistemas de Informação para Gestão - sg',
          'Projeto Pratico em Administração II',
        ],
      },
      {
        title: 'TRABALHO DE CONCLUSÃO DE CURSO',
        contents: ['TRABALHO DE CONCLUSÃO DE CURSO'],
      },
    ],
  },
  {
    id: '3213',
    imgUrl: image.agrimensura,
    curriculum: [
      {
        title: 'Gerais',
        contents: [
          'Nivelamento de Matemática',
          'Raciocínio Lógico',
          'Geografia Física do Brasil',
          'Geografia e Recursos Hídricos',
          'Interpretação de Desenho Técnico',
          'Introdução a Segurança do Trabalho',
          'Projeto Civil Auxiliado por Computador',
          'Introdução ao Autocad 2D',
          'Topografia Fundamentos',
          'Direito e Legislação Ambiental',
          'Laboratórios I - Medindo e Classificando / Ângulos Sistema de Projeções',
        ],
      },
      {
        title: 'Auxiliar em Topografia - CBO 3181-10',
        contents: [
          'Princípios da Climatologia e Hidrologia',
          'Licenciamento Ambiental',
          'Hidrogeologia',
          'Topografia',
          'Desenho Técnico I',
          'Geologia I',
          'Introdução à Gestão Ambiental',
          'Climatologia',
          'Laboratórios II - Topografia: Nivelamento com Mangueira / Topografia: Medição com Trena / Topografia: Instalação de Teodolito Eletrônico',
        ],
      },
      {
        title: 'Auxiliar em Cartógrafo - CBO 2148-10',
        contents: [
          'Topografia Aplicada',
          'Geomática Topográfica',
          'Geologia II',
          'Avaliação de Impactos Ambientais I',
          'Desenho Técnico II',
          'Cartografia',
          'Geoprocessamento',
          'Pedologia',
          'Laboratórios III- Topografia: Locação de Obra (Cavalete) / Topografia: Locação de Obra (Gabarito) / Topografia: Levantamento de Curvas de Nível',
        ],
      },
      {
        title: 'Auxiliar em Agrimensura - CBO 3123-05',
        contents: [
          'Avaliação de Impactos Ambientais II',
          'Cartografia Digital e Sensoriamento Remoto',
          'Topografia de Minas',
          'Mineralogia',
          'Topografia e Geoprocessamento',
          'Recuperação de Áreas Degradadas',
          'Prospecção Geofísica e Geoquímica',
          'Laboratórios IV - Topografia: Movimentação de Solo // Topografia: Diferenças entre SIG e CAD / Caracterização de Solos: Determinação da Umidade Natural / Caracterização de Solos: Curva Granulométrica',
        ],
      },
      {
        title: 'TRABALHO DE CONCLUSÃO DE CURSO DE AGRIMENSURA',
        contents: ['Trabalho de Conclusão de Curso Final'],
      },
    ],
  },
  {
    id: '4801',
    imgUrl: image.agro,
    videoUrl: 'tWUcyhi8bwE',
    curriculum: [
      {
        title: 'AUXILIAR ADMINISTRATIVO – CBO 4110-05',
        contents: [
          'Introdução à Administração',
          'Matemática Financeira',
          'Introdução à Matemática Financeira',
          'Teorias Aplicadas na Administração',
          'Administração Financeira',
          'Introdução à Agronomia e ao Agronegócio',
          'Empreendedorismo',
          'Administração de Pessoal',
          'Geoprocessamento',
          'Geologia',
          'Responsabilidade Social e Meio Ambiente Agro',
          'Atividade de Pesquisa e Prática em Agro I',
        ],
      },
      {
        title: 'AUXILIAR FINANCEIRO - CBO 2522-05',
        contents: [
          'Introdução à Gestão do Agronegócio',
          'Ecologia',
          'Cadeias Produtivas do Agronegócio I',
          'Princípios da Climatologia e Hidrologia',
          'Fundamentos da Extensão Rural',
          'Direito Aplicado ao Agronegócio',
          'Modelos de Gestão',
          'Ciência do Solo e Fertilidade',
          'Gestão da Qualidade Total',
          'Recuperação de Áreas Degradadas',
          'Atividade de Pesquisa e Prática em Agro II',
        ],
      },
      {
        title: 'AUXILIAR DE ESCRITÓRIO AMBIENTAL – CBO – 4110-05',
        contents: [
          'Assistência Técnica e Extensão Rural',
          'Economia Rural',
          'Cadeias Produtivas do Agronegócio II',
          'Licenciamento Ambiental',
          'Agricultura Climaticamente Inteligente e Sustentabilidade',
          'Planejamento Ambiental Agro',
          'Atividade de Pesquisa e Prática em Agro III',
        ],
      },
      {
        title: 'ANALISTA DE AGRONEGÓCIOS CBO 2512-10',
        contents: [
          'Logística e Suprimento de Distribuição Agro',
          'Gestão de Transporte e Tráfego Agro',
          'Planejamento Estratégico Agro',
          'Políticas Públicas para o Agronegócio',
          'Custos de Produção no Agronegócio',
          'Cadeias Produtivas do Agronegócio III',
          'Gestão da Produção Agro',
          'Atividade de Pesquisa e Prática em Agro IV',
        ],
      },
      {
        title: 'TRABALHO DE CONCLUSÃO DE CURSO EM AGRONEGÓCIOS',
        contents: ['TRABALHO DE CONCLUSÃO DE CURSO EM AGRONEGÓCIOS'],
      },
    ],
  },
  {
    id: '7282',
    imgUrl: image.alimentEscolar,
    videoUrl: 'Ei7ln8GrRRA',
    curriculum: [
      {
        title: 'Auxiliar Administrativo – CBO 4110-05',
        contents: [
          'Introdução a Administração',
          'Empreendedorismo',
          'Introdução ao Empreendedorismo',
          'Teorias Aplicadas na Administração',
          'Matemática Financeira',
          'Introdução a Matemática Financeira',
          'Gestão da Qualidade Total',
          'Modelos de Gestão',
          'Organização, Sistemas e Métodos',
          'Processos Gerenciais',
        ],
      },
      {
        title: 'Gerais I',
        contents: [
          'Administração de Serviços de Alimentação',
          'Habilidades Básicas em Cozinha',
          'Políticas Públicas de Alimentação e Nutrição',
          'Microbiologia dos Alimentos',
          'Bioquímica dos Alimentos',
          'Alimentos de Origem Animal',
        ],
      },
      {
        title: 'Auxiliar de Estoque – CBO 4141-25',
        contents: [
          'Gestão de Custos, Riscos e Perdas',
          'Gestão de Estoques e Compras',
          'Gestão de Armazenamento, Estoque e Distribuição',
        ],
      },
      {
        title: 'Auxiliar de Serviços de Alimentação - CBO 5135-05',
        contents: [
          'Alimentos de Origem Vegetal',
          'Microbiologia e Legislação de Alimentos',
          'Higiene e Controle Sanitário de Alimentos',
          'Segurança, Saúde e Alimentação Escolar',
          'Controle e Qualidade dos Alimentos',
          'Tecnologia de Alimentos',
        ],
      },
      {
        title: 'Gerais II',
        contents: [
          'Gastronomia Brasileira I',
          'Cozinha Quente e Cozinha Fria',
          'Cozinha Quente',
          'Confeitaria',
          'Inovação e Tecnologia em Alimentação',
        ],
      },
      {
        title: 'Trabalho de Conclusão de Curso Alimentação Escolar',
        contents: ['Trabalho de Conclusão de Curso Alimentação Escolar'],
      },
      {
        title: 'Estágio obrigatório de 100h',
        contents: ['Estágio obrigatório de 100h'],
      },
    ],
  },
  {
    id: '4802',
    imgUrl: image.automacaoInd,
    videoUrl: 'TSMsiN3NpF0',
    curriculum: [
      {
        title: 'Auxiliar Eletrotécnico – CBO 3131-05',
        contents: [
          'Eletricidade I',
          'Eletrônica Básica',
          'Instrumentação (EWB)',
          'Instrumentação Eletrônica - Multímetro',
          'Instrumentação Eletrônica - Osciloscópio',
          'Introdução ao Autocad 2D',
          'Multisim 13 Fundamentos',
          'Nivelamento de Física',
          'Nivelamento de Matemática',
          'Princípios de Eletromagnetismo',
          'Princípios de Eletrônica Analógica',
          'Microprocessadores',
        ],
      },
      {
        title:
          'Auxiliar de Desenho Técnico em Eletroeletrônica – CBO – 3180-05',
        contents: [
          'Multisim Avançado - Técnicas de Simulação',
          'Leitura e Interpretação de Diagramas Eletrônicos',
          'Introdução à Mesa Eletrônica',
          'Eletricidade II',
          'Eletricidade III',
          'Eletrônica Digital',
          'Eletrônica Analogica',
          'Instrumentação e Automação Industrial',
          'Algoritimos e Programação',
          'Logica de Programação',
          'CLP - Controladores Lógicos Programáveis',
          'CLP Fundamentos',
          'Projeto Prático em Automação Industrial I',
        ],
      },
      {
        title: 'Auxiliar em Sistema automação industrial– CBO 3132-15',
        contents: [
          'Eletrônica Industrial Avançada',
          'Acionamentos Elétricos',
          'Instrumentação',
          'Sensores Elétricos e Eletrônicos',
          'Sistemas Microcontrolados',
          'Instalações Elétricas Industriais',
          'Sistemas hidráulicos e pneumáticos',
          'Projeto Prático em Automação Industrial III',
        ],
      },
      {
        title: 'Gerais',
        contents: [
          'Programação CNC para Torneamento',
          'Eletrônica Digital Fundamentos',
          'Eletrônica Industrial',
          'Automação Industrial',
          'Fundamentos de Automação Industrial',
          'Eletrônica Industrial - Princípios Básicos',
          'Circuitos de Interface e Relógios Digitais',
          'Projeto Prático em Automação Industrial II',
        ],
      },
      {
        title: 'Todos os Blocos',
        contents: ['Laboratório de INSTALAÇÕES ELÉTRICAS'],
      },
      {
        title: 'Trabalho de Conclusão de Curso Automação Industrial',
        contents: ['Trabalho de Conclusão de Curso Automação Industrial'],
      },
    ],
  },
  {
    id: '27',
    imgUrl: image.contabilidade,
    videoUrl: 'XO-v0HEx1Tc',
    curriculum: [
      {
        title: 'AUXILIAR ADMINISTRATIVO – CBO 4110-05',
        contents: [
          'Introdução a Administração',
          'Empreendedorismo',
          'Introdução ao Empreendedorismo',
          'Teorias Aplicadas na Administração',
          'Matemática Financeira',
          'Introdução a Matemática Financeira',
          'Gestão da Qualidade Total',
          'Modelos de Gestão',
          'Organização, Sistemas e Métodos',
          'Processos Gerenciais',
        ],
      },
      {
        title: 'AUXILIAR DE SERVIÇOS CONTÁBEIS - CBO 4131-10',
        contents: [
          'Teoria da Contabilidade',
          'Contabilidade I',
          'Contabilidade Básica',
          'Análise de Custo I',
          'Gestão de Custos I',
          'Ética e Legislação Contábil',
          'Fundamentos da Contabilidade',
          'Contabilidade para não Contadores',
        ],
      },
      {
        title: 'ASSISTENTE DE SERVIÇO DE CONTABILIDADE - CBO 4131-10',
        contents: [
          'Contabilidade Geral',
          'Gestão de Custos II',
          'Contabilidade II',
          'Contabilidade Avançada',
          'Contabilidade Pública Avançada',
          'Contabilidade e Orçamento Público I',
          'Contabilidade Social',
          'Orçamentos, Custos e Finanças no Setor Público',
          'Contabilidade Tributária I',
        ],
      },
      {
        title: 'ASSISTENTE DE ANÁLISE CONTÁBIL - CBO 2522-10',
        contents: [
          'Contabilidade do Terceiro Setor',
          'Contabilidade de Folha de Pagamento',
          'Fundamentos de Auditoria Contábil',
          'Fundamentos de Controladoria',
          'Perícia, Avaliação e Arbitragem',
          'Análise de Custo II',
          'Contabilidade Tributária II',
          'Contabilidade e Orçamento Público II',
        ],
      },
      {
        title: 'TRABALHO DE CONCLUSÃO DE CURSO DE CONTABILIDADE',
        contents: ['Trabalho Final de Conclusão'],
      },
    ],
  },
  {
    id: '19',
    imgUrl: image.edificacao,
    videoUrl: 'VePcn68V9W4',
    curriculum: [
      {
        title: 'Auxiliar Administrativo em Edificações – CBO – 4110-05',
        contents: [
          'Construção Civil',
          'Interpretação de Desenho Técnico',
          'Introdução a Segurança do Trabalho',
          'Projeto Civil Auxiliado por Computador',
          'Introdução ao Autocad 2D',
          'Desenho Técnico I',
          'Desenho Técnico na Construção Civil',
          'Materiais e Técnicas de Construção I',
          'Técnicas de Construção',
          'BIM - Conceitos, Tecnologia e Processos',
          'Desenho Técnico II',
          'Materiais e Técnicas de Construção II - SG',
          'Sketchup: Fundamentos',
          'Revit: Fundamentos',
          'Materiais de Construção I',
          'Projeto Prático em Edificações I',
        ],
      },
      {
        title: 'Auxiliar de Desenho Técnico – CBO – 3180-05',
        contents: [
          'Concreto Armado',
          'Mecânica dos Solos',
          'Materiais de Construção II',
          'Topografia Fundamentos',
          'Alvenaria',
          'Geomática: Topografia',
          'Topografia Aplicada',
          'Autocad: Parametrização, blocos dinâmicos e escalas',
          'Autocad 2017: Planta baixa',
        ],
      },
      {
        title: 'Auxiliar de Manutenção de Edificações – CBO – 5143-10',
        contents: [
          'Fundações',
          'Instalações Elétricas e de Comunicação',
          'Instalações Hidráulicas',
          'Conceitos de Projetos Elétricos Residenciais',
          'Instalações Hidráulicas - Água Fria e Quente',
          'Instalações Hidráulicas - Esgoto e Drenagem',
          'Instalações Hidrossanitárias, de Gás e Combate a Incêndios',
          'Saneamento e Instalações Hidráulicas Prediais',
          'Visita Técnica em Edificações I',
          'Projeto Prático em Edificações II',
        ],
      },
      {
        title: 'Auxiliar de Execução e Gestão de Obras – CBO – 5143-25',
        contents: [
          'Fundações e Obras de Contenção',
          'Processos Construtivos',
          'Pintura e Revestimento',
          'Gestão de Obras',
          'Estabilidade',
          'Estruturas',
          'Esquadrias',
          'Construções Especiais',
          'Gestão de Obras e Patologia das Estruturas',
          'Projetos Práticos em Edificações III',
        ],
      },
      {
        title: 'Trabalho de Conclusão de Curso - Edificações',
        contents: ['Trabalho de Conclusão de Curso - Edificações'],
      },

      {
        title: 'Laboratório de Práticas Específicas de Edificações',
        contents: ['Laboratório de Práticas Específicas de Edificações'],
      },
    ],
  },
  {
    id: '4805',
    imgUrl: image.eletronica,
    videoUrl: '-JWvkTLvm5A',
    curriculum: [
      {
        title: 'Auxiliar Eletrotécnico – CBO 3131-05',
        contents: [
          'Eletricidade I',
          'Eletrônica Básica',
          'Instrumentação (EWB)',
          'Instrumentação Eletrônica - Multímetro',
          'Instrumentação Eletrônica - Osciloscópio',
          'Introdução ao Autocad 2D',
          'Multisim 13 Fundamentos',
          'Nivelamento de Física',
          'Nivelamento de Matemática',
          'Princípios de Eletromagnetismo',
          'Princípios de Eletrônica Analógica',
          'Projeto Prático em Eletricidade I',
        ],
      },
      {
        title:
          'Auxiliar de Desenho Técnico em Eletroeletrônica – CBO – 3180-05',
        contents: [
          'Multisim Avançado - Técnicas de Simulação',
          'Leitura e Interpretação de Diagramas Eletrônicos',
          'Introdução à Mesa Eletrônica',
          'Eletricidade II',
          'Eletricidade III',
          'Eletrônica Digital',
          'Eletrônica Analógica',
          'CLP - Controladores Lógicos Programáveis',
          'CLP Fundamentos',
          'Eletrônica Básica Exemplos Práticos',
          'Projeto Prático em Eletrônica I',
        ],
      },
      {
        title:
          'Auxiliar de Montador de Equipamentos Eletroeletrônicos – CBO – 7311-10',
        contents: [
          'Eletrônica Digital Fundamentos',
          'Eletrônica Industrial',
          'Algoritmos e Programação',
          'Lógica de Programação',
          'Fundamentos de Automação Industrial',
          'Máquinas Elétricas',
          'Manutenção Elétrica Industrial',
          'Eletrônica Industrial - Princípios Básicos',
          'Circuitos de Interface e Relógios Digitais',
          'Projeto Prático em Eletrônica II',
        ],
      },
      {
        title: 'Auxiliar em Eletrônica – CBO 3132-15',
        contents: [
          'Eletrônica Industrial Avançada',
          'Acionamentos Elétricos',
          'Amplificadores Operacionais',
          'Comunicação Eletrônica',
          'Eletrônica Aplicada - Circuitos Transistorizados',
          'Sensores Elétricos e Eletrônicos',
          'Sistemas Microcontrolados',
          'Circuitos Impressos Concepção e Fabricação na Prática',
          'Projeto Prático em Eletrônica III',
        ],
      },
      {
        title: 'Trabalho de Conclusão de Curso Eletrônica',
        contents: ['Trabalho de Conclusão de Curso Eletrônica'],
      },
    ],
  },
  {
    id: '20',
    imgUrl: image.eletrotec,
    videoUrl: 'Op7QhyhWTbA',
    curriculum: [
      {
        title: 'AUXILIAR ELETROTÉCNICO – CBO 3131-05',
        contents: [
          'Eletricidade I',
          'Eletrônica Básica',
          'Instrumentação (EWB)',
          'Instrumentação Eletrônica - Multímetro',
          'Instrumentação Eletrônica - Osciloscópio',
          'Introdução ao Autocad 2D',
          'Multisim 13 Fundamentos',
          'Nivelamento de Física',
          'Nivelamento de Matemática',
          'Princípios de Eletromagnetismo',
          'Princípios de Eletrônica Analógica',
          'Projeto Prático em Eletricidade I',
        ],
      },
      {
        title:
          'AUXILIAR DE DESENHO TÉCNICO EM ELETROELETRÔNICA – CBO – 3180-05',
        contents: [
          'Multisim Avançado - Técnicas de Simulação',
          'Leitura e Interpretação de Diagramas Eletrônicos',
          'Introdução à Mesa Eletrônica',
          'Eletricidade II',
          'Eletricidade III',
          'Eletrônica Digital',
          'Eletrônica Analógica',
          'CLP - Controladores Lógicos Programáveis',
          'CLP Fundamentos',
          'Projeto Prático em Eletrotécnica I',
        ],
      },
      {
        title: 'AUXILIAR DE INSTALAÇÕES PREDIAIS E INDUSTRIAIS – CBO – 7311-10',
        contents: [
          'Acionamentos Elétricos',
          'Manutenção Elétrica Industrial',
          'Conceitos de Projetos Elétricos Residenciais',
          'Instalações Elétricas',
          'Eletrônica Industrial - Princípios Básicos',
          'Equipamentos Elétricos de Potência',
          'Fundamentos de Automação Industrial',
          'Máquinas elétricas',
          'Projeto Prático em Eletrotécnica II',
        ],
      },
      {
        title:
          'AUXILIAR DE MONTADOR DE EQUIPAMENTOS ELETROELETRÔNICOS – CBO – 7311-10',
        contents: [
          'Eletrônica Industrial Avançada',
          'Algoritimos e Programação',
          'Logica de Programação',
          'Geração e Distribuição de Energia Elétrica',
          'Instalações Elétricas Industriais',
          'Sensores Elétricos e Eletrônicos',
          'Sistemas Microcontrolados',
          'Projeto Prático em Eletrotécnica III',
        ],
      },
      {
        title: 'TRABALHO DE CONCLUSÃO DE CURSO ELETROTÉCNICA',
        contents: ['Trabalho de Conclusão de Curso Eletrotécnica'],
      },
    ],
  },
  {
    id: '15',
    imgUrl: image.estetica,
    videoUrl: 'vY_RHk3AKFQ',
    curriculum: [
      {
        title: 'Gerais I',
        contents: [
          'Introdução e Fundamentos da Estética e Cosmética',
          'Anatomofisiologia Aplicada à Estética',
          'Estética dos Anexos Cutâneos',
          'Bioética e Biossegurança Aplicada',
          'Estética Integrada e Humanizada',
          'Marketing e Gestão em Serviços de Estética e Cosmética',
          'Empreendedorismo',
        ],
      },
      {
        title: 'Gerais II',
        contents: [
          'Bases Farmacológicas e Interações Medicamentosas na Estética',
          'Cosmetologia Aplicada I',
          'Princípios Ativos em Estética',
          'Cosmetologia Aplicada II',
          'Práticas de Laboratórios I',
        ],
      },
      {
        title: 'Básicas',
        contents: [
          'Habilidades e Técnicas de Depilação e Epilação',
          'Design de Cílios e Sobrancelhas',
          'Design de Sobrancelha',
          'Recursos Estéticos e Cosméticos Capilares',
          'Colorimetria e Texturização Capilar',
          'Visagismo',
          'Nutrição',
          'Estética em Eventos',
          'Práticas de Laboratórios II',
        ],
      },
      {
        title: 'Auxiliar de Esteticista Facial - CBO 3221-30',
        contents: [
          'Estética Facial',
          'Procedimentos em Estética Facial',
          'Recursos Estéticos Manuais',
          'Drenagem Linfática',
          'Disfunções Dermatológicas Aplicadas à Estética',
          'Práticas de Laboratórios III',
        ],
      },
      {
        title: 'Auxiliar de Esteticista Corporal - CBO 3221-30',
        contents: [
          'Métodos e Técnicas de Avaliação Estética',
          'Massoterapia',
          'Podologia',
          'Fundamentos de Eletroestética',
          'Eletroterapia Facial e Corporal Básica',
          'Eletroterapia Facial e Corporal Avançada',
          'Estética Aplicada à Cirurgia Plástica',
          'Procedimentos Pré e Pós-Cirurgia Estética',
          'Práticas de Laboratórios IV',
        ],
      },
      {
        title: 'Prática Estágio Curricular (100 horas) - Estágio Obrigatório',
        contents: [
          'Prática Estágio Curricular (100 horas) - Estágio Obrigatório',
        ],
      },
      {
        title: 'Trabalho de Conclusão de Curso em Estética',
        contents: ['Trabalho de Conclusão de Curso em Estética'],
      },
    ],
  },
  {
    id: '4806',
    imgUrl: image.financas,
    videoUrl: '2cMOEa9df-o',
    curriculum: [
      {
        title: 'AUXILIAR ADMINISTRATIVO – CBO 4110-05',
        contents: [
          'Introdução à Administração',
          'Empreendedorismo',
          'Introdução ao Empreendedorismo',
          'Teorias Aplicadas na Administração',
          'Matemática Financeira',
          'Introdução à Matemática Financeira',
          'Gestão da Qualidade Total',
          'Modelos de Gestão',
          'Organização, Sistemas e Métodos',
          'Processos Gerenciais',
        ],
      },
      {
        title: 'AUXILIAR FINANCEIRO - CBO 2522-05',
        contents: [
          'Administração Financeira',
          'Fundamentos da Economia',
          'Economia',
          'Mercado de Capitais',
          'Economia Política I',
          'Macroeconomia',
          'Gestão e Análise Financeira',
          'Projeto Prático em Finanças I',
        ],
      },
      {
        title: 'ENCARREGADO DE CONTROLE FINANCEIRO - CBO 4102-35',
        contents: [
          'Análise das Demonstrações Financeiras',
          'Análise de Riscos',
          'Gerenciamento de Riscos',
          'Análise de Investimento e Fontes de Financiamento',
          'Avaliação de Investimento',
          'Economia Política II',
          'Projeto Prático em Finanças II',
        ],
      },
      {
        title: 'TRABALHO DE CONCLUSÃO DE CURSO DE FINANÇAS',
        contents: ['TRABALHO DE CONCLUSÃO DE CURSO DE FINANÇAS'],
      },
    ],
  },
  {
    id: '7278',
    imgUrl: image.turismoInt,
    videoUrl: '5000sjH-11o',
    curriculum: [
      {
        title: 'BLOCO 1',
        contents: [
          'Antropologia e Cultura',
          'Teoria da História e Historiografia',
          'Plano de Negocio',
          'Estudos Culturais e Antropológicos',
        ],
      },
      {
        title: 'BLOCO 2',
        contents: [
          'História da América: Origem e Colonização',
          'Ingles Avançado - Pratico - Internacional',
          'Comprovação de Proficiencia em Idioma',
          'Projeto Pratico em Turismo Internacional',
        ],
      },
      {
        title: 'Trabalho de Conclusão de Curso de Guia de Turismo',
        contents: ['Trabalho de Conclusão de Curso de Guia de Turismo'],
      },
    ],
  },
  {
    id: '7280',
    imgUrl: image.turismo3,
    videoUrl: '5000sjH-11o',
    curriculum: [
      {
        title: 'AUXILIAR DE ESCRITÓRIO DE AGÊNCIA DE TURISMO - CBO 4110-05',
        contents: [
          'INTRODUÇÃO A ADMINISTRAÇÃO',
          'EMPREENDEDORISMO',
          'MATEMÁTICA FINANCEIRA',
          'MARKETING DE SERVIÇOS',
          'SERVIÇOS DE TURISMO E VIAGENS',
          'REVISÃO GEOGRAFIA GERAL',
          'REVISÃO HISTORIA GERAL',
          'MARKETING DIGITAL',
          'FUNDAMENTOS DO ESPANHOL',
          'FUNDAMENTOS DO INGLÊS',
          'PROJETO PRÁTICO EM TURISMO I',
        ],
      },
      {
        title: 'AUXILIAR DE ORGANIZAÇÃO DE EVENTOS - CBO 3548-20',
        contents: [
          'ELABORAÇÃO DE ROTEIROS E PACOTES',
          'ANTROPOLOGIA E CULTURA',
          'INTRODUÇÃO A TÉCNICAS DE NEGOCIAÇÃO',
          'GESTÃO DE VENDAS E NEGOCIAÇÃO',
          'TEORIA DA HISTÓRIA E HISTORIOGRAFIA',
          'GESTÃO DA QUALIDADE TOTAL',
          'MARKETING DE SERVIÇOS',
          'PROJETO PRÁTICO EM TURISMO II',
        ],
      },
      {
        title: 'AUXILIAR DE CONDUTOR DE ATRATIVOS NATURAIS - CBO 5115-05',
        contents: [
          'ATRATIVOS NATURAIS',
          'HISTÓRIA DA ARTE',
          'MULTIMODALIDADE TURÍSTICA',
          'ANÁLISE DE MÍDIAS SOCIAIS',
          'INGLÊS AVANÇADO – PRATICO NAC / REG',
          'PRIMEIROS SOCORROS',
          'PLANO DE NEGÓCIOS',
          'PROJETO PRÁTICO EM TURISMO III',
        ],
      },
      {
        title:
          'TRABALHO DE CONCLUSÃO DE CURSO DE GUIA DE TURISMO NACIONAL / REGIONAL',
        contents: [
          'TRABALHO DE CONCLUSÃO DE CURSO DE GUIA DE TURISMO NACIONAL / REGIONAL',
        ],
      },
      {
        title: 'FORMAÇÃO COMPLEMENTAR - GUIA INTERNACIONAL',
        contents: [
          'ESTUDOS CULTURAIS E ANTROPOLÓGICOS',
          'HISTÓRIA DA AMÉRICA : ORIGEM E COLONIZAÇÃO',
          'INGLÊS AVANÇADO – PRATICO – INTERNACIONAL – DR',
          'COMPROVAÇÃO DE PROFICIÊNCIA EM IDIOMA',
          'PROJETO PRÁTICO EM TURISMO INTERNACIONAL',
        ],
      },
      {
        title:
          'TRABALHO DE CONCLUSÃO DE CURSO DE GUIA DE TURISMO INTERNACIONAL',
        contents: [
          'TRABALHO DE CONCLUSÃO DE CURSO DE GUIA DE TURISMO INTERNACIONAL',
        ],
      },
    ],
  },
  {
    id: '7281',
    imgUrl: image.turismo,
    videoUrl: 'coraUkodpDc',
    curriculum: [
      {
        title: 'Auxiliar de Escritório de Agência de Turismo - CBO 4110-05',
        contents: [
          'Introdução a Administração',
          'Empreendedorismo',
          'Matemática Financeira',
          'Marketing de Serviços',
          'Serviços de Turismo e Viagens',
          'Revisão Geografia Geral',
          'Revisão História Geral',
          'Marketing Digital',
          'Fundamentos do Espanhol',
          'Fundamentos do Inglês',
          'Projeto Prático em Turismo I',
        ],
      },
      {
        title: 'Auxiliar de Organização de Eventos - CBO 3548-20',
        contents: [
          'Elaboração de Roteiros e Pacotes',
          'Antropologia e Cultura',
          'Introdução a Técnicas de Negociação',
          'Gestão de Vendas e Negociação',
          'Teoria da História e Historiografia',
          'Gestão da Qualidade Total',
          'Marketing de Serviços voltado ao Turismo',
          'Projeto Prático em Turismo II',
        ],
      },
      {
        title: 'Auxiliar de Condutor de Atrativos Naturais - CBO 5115-05',
        contents: [
          'Historia da Arte',
          'Primeiros Socorros',
          'Plano de Negocio',
          'Projeto Pratico em Turismo III',
          'Atrativos Naturais',
        ],
      },
      {
        title: 'Gerais',
        contents: [
          'Multimodalidade Turística',
          'Análise de Mídias Sociais',
          'Ingles Avançado - Pratico  Nac / Reg',
        ],
      },
      {
        title: 'TRABALHO DE CONCLUSÃO DE CURSO DE GUIA DE TURISMO',
        contents: ['Trabalho de Conclusão de Curso de Guia de Turismo'],
      },
    ],
  },
  {
    id: '7279',
    imgUrl: image.turismoAgua,
    videoUrl: 'LsnjBF415nQ',
    curriculum: [
      {
        title: 'Auxiliar de Escritório de Agência de Turismo - CBO 4110-05',
        contents: [
          'Introdução a Administração',
          'Empreendedorismo',
          'Marketing de Serviços',
          'Serviços de Turismo e Viagens',
          'Revisão Geografia Geral',
          'Revisão História Geral',
          'Fundamentos do Inglês',
          'Projeto Prático em Turismo I',
        ],
      },
      {
        title: 'Auxiliar de Organização de Eventos - CBO 3548-20',
        contents: [
          'Elaboração de Roteiros e Pacotes',
          'Antropologia e Cultura',
          'Gestão de Vendas e Negociação',
          'Teoria da História e Historiografia',
          'Marketing de Serviços voltado ao Turismo',
          'Projeto Prático em Turismo II',
        ],
      },
      {
        title: 'Auxiliar de Condutor de Atrativos Naturais - CBO 5115-05',
        contents: [
          'Historia da Arte',
          'Primeiros Socorros',
          'Plano de Negocio',
          'Projeto Pratico em Turismo III',
          'Atrativos Naturais',
        ],
      },
      {
        title: 'Trabalho de conclusão de curso',
        contents: ['Trabalho de conclusão de curso'],
      },
    ],
  },
  {
    id: '6311',
    imgUrl: image.infoInternet,
    videoUrl: 'xn8RNBSE5Yw',
    curriculum: [
      {
        title: 'AUXILIAR DE INSTRUTÓRIA DE INFORMÁTICA CBO – 2332-25',
        contents: [
          'Fundamentos Computacionais',
          'Tecnologias de Comunicação e de Informação',
          'Fundamentos de Segurança da Informação',
          'Sistemas Operacionais',
          'Introdução ao Hardware - Montagem e Manutenção de Computadores',
          'Introdução à lógica de programação',
          'Introdução a Redes de Computadores',
          'Introdução ao Banco de Dados',
          'Projeto Pratico I em Informática',
        ],
      },
      {
        title:
          'AUXILIAR TÉCNICO DE APOIO AO USUÁRIO DE INFORMÁTICA – CBO – 3172-10',
        contents: [
          'Algoritmos e programação',
          'Fundamentos de Redes de Computadores',
          'Cabeamento Estruturado',
          'Comunicação de Dados',
          'Introdução a Técnicas em Programação',
          'Introdução ao HTML5',
          'HTML5 e CSS Fundamentos',
          'Projeto Pratico II em Informática',
        ],
      },
      {
        title: 'AUXILIAR DE OPERAÇÕES DE SISTEMAS DE INFORMÁTICA CBO – 3722-05',
        contents: [
          'Modelagem de Dados e Instruções SQL',
          'Ferramentas de Desenvolvimento Web',
          'Administração de Banco de Dados',
          'Introdução a Big Data e Internet das Coisas (IoT)',
          'Programação e Banco de Dados',
          'Lógica de Programação',
          'CSS3 Fundamentos',
          'PHP com MySQL',
          'Desenvolvimento de Sistemas com PHP',
          'Desenvolvimento para Dispositivos Móveis I',
          'Projeto Pratico III em Informática',
        ],
      },
      {
        title:
          'AUXILIAR DE OPERAÇÕES DE SISTEMAS DE INFORMÁTICA CBO – 3722-05 PARTE II',
        contents: [
          'Desenvolvimento para Dispositivos Móveis II',
          'Introdução à programação em linguagem JAVA',
          'Programação em JAVA',
          'Programação Java para Web',
          'Projeto Pratico IV em Informática',
        ],
      },
      {
        title: 'TRABALHO DE CONCLUSÃO DE CURSO DE INFORMÁTICA PARA INTERNET',
        contents: [
          'Trabalho de Conclusão de Curso em Informatica para Internet',
        ],
      },
    ],
  },
  {
    id: '39',
    imgUrl: image.logistica,
    videoUrl: 'qfmGwPrl3w0',
    curriculum: [
      {
        title: 'AUXILIAR ADMINISTRATIVO – CBO 4110-05',
        contents: [
          'Introdução a Administração',
          'Empreendedorismo',
          'Introdução ao Empreendedorismo',
          'Teorias Aplicadas na Administração',
          'Matemática Financeira',
          'Introdução a Matemática Financeira',
          'Gestão da Qualidade Total',
          'Modelos de Gestão',
          'Organização, Sistemas e Métodos',
          'Processos Gerenciais',
        ],
      },
      {
        title: 'AUXILIAR FINANCEIRO – CBO 4131-10',
        contents: [
          'Logística I',
          'Gestão de Custos, Riscos e Perdas',
          'Gerenciamento de custos logísticos',
          'Gestão de empresas e transportes',
          'Gestão de Estoques e Compras',
        ],
      },
      {
        title: 'ATENDENTE DE INFORMAÇÕES – CBO 4223-15',
        contents: [
          'Armazenagem e movimentação de cargas I',
          'Canais de Distribuição Física',
          'Sistemas de Transportes Modais',
          'Logística e Distribuição',
        ],
      },
      {
        title: 'AUXILIAR DE ESTOQUE – CBO 4141-25',
        contents: [
          'Logística II',
          'Armazenagem e movimentação de cargas II',
          'Operações Logísticas Integradas',
        ],
      },
      {
        title: 'AUXILIAR DE LOGÍSTICA – CBO 4141-40',
        contents: [
          'Logística Reversa',
          'Logística Internacional',
          'Gestão de Armazenamento, Estoque e Distribuição',
          'Gestão da Tecnologia e Informação em Logística',
        ],
      },
      {
        title: 'TRABALHO DE CONCLUSÃO DE CURSO DE LOGÍSTICA',
        contents: ['Trabalho de Conclusão de Curso Logística'],
      },
    ],
  },
  {
    id: '4808',
    imgUrl: image.marketing,
    videoUrl: 'wTxstaJH4Mg',
    curriculum: [
      {
        title: 'AUXILIAR ADMINISTRATIVO – CBO 4110-05',
        contents: [
          'Introdução à Administração',
          'Empreendedorismo',
          'Introdução ao Empreendedorismo',
          'Teorias Aplicadas na Administração',
          'Matemática Financeira',
          'Introdução à Matemática Financeira',
          'Gestão da Qualidade Total',
          'Modelos de Gestão',
          'Organização, Sistemas e Métodos',
          'Processos Gerenciais',
        ],
      },
      {
        title: 'ANALISTA DE MARKETING - CBO 1423-35',
        contents: [
          'Administração de Marketing I',
          'Publicidade e Concepções Teóricas',
          'Análise de Mídias Sociais',
          'Introdução ao Direito do Consumidor',
          'Marketing Digital',
          'Marketing de Serviços',
          'Comércio Eletrônico',
          'Gestão de Marcas e Relacionamento com o Cliente',
          'Projeto Prático em Marketing I',
        ],
      },
      {
        title: 'AUXILIAR DE COORDENAÇÃO DE MARKETING - CBO 1423-35',
        contents: [
          'Administração de Marketing II',
          'Gestão de Marcas',
          'Comportamento do Consumidor',
          'Análise de Cenários e Planejamento Mercadológico',
          'Pesquisa de Marketing',
          'Pesquisa Mercadológica',
          'Consultoria de Marketing',
          'Projeto Prático em Marketing II',
        ],
      },
      {
        title: 'Trabalho de Conclusão de Curso em Marketing',
        contents: ['Trabalho de Conclusão de Curso em Marketing'],
      },
    ],
  },
  {
    id: '21',
    imgUrl: image.mecanica,
    videoUrl: '0JDpFbDaQ74',
    curriculum: [
      {
        title: 'INTRODUÇÃO A MECÂNICA',
        contents: [
          'Introdução a Mecânica',
          'Funções e Trigonometria Básica para Mecânica',
          'Matemática Essencial para Mecânica',
          'Mecânica Técnica',
          'Desenho Técnico Mecânico',
          'Introdução ao AutoCAD 2D',
          'Ciência dos Materiais I',
          'Introdução à Ciência dos Materiais',
          'Metrologia I',
          'Introdução a Eletrotécnica',
          'Introdução a Segurança do Trabalho',
          'Primeiros Socorros',
        ],
      },
      {
        title: 'ASSISTENTE DE DESENHO DE FERRAMENTAS MECÂNICAS',
        contents: [
          'SolidWorks - Peças',
          'SolidWorks - Detalhamento Básico',
          'SolidWorks - Montagem Básica',
          'AutoCAD Mechanical 2017 Essencial',
          'Metrologia II',
          'Ciência dos Materiais II',
          'Resistência dos Materiais I',
          'Instrumentação',
          'Metrologia Essencial - Paquímetro/Micrômetro',
          'Mecânica dos Fluidos',
          'Termodinâmica',
          'Conceitos e Projeto para Rede de Ar Industrial',
        ],
      },
      {
        title: 'ASSISTENTE DE DESENHISTA PROJETISTA DE MÁQUINAS',
        contents: [
          'Ensaio e Caracterização de Materiais',
          'Processos de Fabricação',
          'Conformação Mecânica e Soldagem',
          'Sistemas Hidráulicos e Pneumáticos',
          'Hidráulica Conceitos Essenciais',
          'Resistência dos Materiais II',
          'Atividade Prática de Mecânica I',
          'Detalhamento de Projetos Mecânicos com Padrão ABNT',
          'Prática de Oficina',
          'Atividade Prática de Mecânica II',
        ],
      },
      {
        title: 'APRENDIZ DE MECÂNICA DE MANUTENÇÃO',
        contents: [
          'Indústria 4.0',
          'Manutenção Industrial',
          'Máquinas Térmicas',
          'Elementos de Máquinas',
          'CLP Fundamentos',
          'Programação CNC para Torneamento',
          'Usinagem',
          'Tecnologia Mecânica - Usinagem Essencial',
          'Detalhamento de Projetos Mecânicos com Padrão ABNT',
          'Prática de Oficina',
          'Atividade Prática de Mecânica II',
        ],
      },
      {
        title: 'TRABALHO DE CONCLUSÃO DE CURSO DE MECÂNICA',
        contents: ['Trabalho de Conclusão de Curso de Mecânica'],
      },
    ],
  },
  {
    id: '3215',
    imgUrl: image.meioAmb,
    videoUrl: 'IIKxshW2QQA',
    curriculum: [
      {
        title: 'AUXILIAR DE ESCRITÓRIO AMBIENTAL – CBO – 4110-05',
        contents: [
          'Introdução à Gestão Ambiental',
          'Nivelamento Biologia',
          'Meio Ambiente',
          'Ecologia',
          'Princípios da Climatologia e Hidrologia',
          'Responsabilidade Socioambiental',
          'Gestão Ambiental I',
          'Direito e legislação ambiental',
          'Licenciamento Ambiental',
          'Controle da Poluição',
          'Visita Técnica em meio ambiente I',
          'Projeto Prático I em meio ambiente',
        ],
      },
      {
        title: 'AUXILIAR DE AGENTE DE DEFESA AMBIENTAL – CBO – 3522-05',
        contents: [
          'Recursos Hídricos',
          'Gestão Ambiental II',
          'Planejamento Urbano e Ambiental',
          'Gerenciamento de unidades de conservação I',
          'Recuperação de Áreas Degradadas',
          'Gestão da Qualidade Total',
          'Visita Técnica em meio ambiente II',
          'Projeto Prático II em meio ambiente',
        ],
      },
      {
        title: 'AUXILIAR DE ANALISTA AMBIENTAL – CBO – 3522-05',
        contents: [
          'Avaliação de Risco e Impactos Ambientais',
          'Sistema de Drenagem Urbana',
          'Sistemas de Tratamento e Abastecimento',
          'Gestão Ambiental III',
          'Gestão Econômica Ambiental',
          'Gerenciamento de unidades de conservação II',
          'Projeto Prático III em meio ambiente',
        ],
      },
      {
        title: 'TRABALHO DE CONCLUSÃO DE CURSO MEIO AMBIENTE',
        contents: ['Trabalho de Conclusão de Curso Meio Ambiente'],
      },
    ],
  },
  {
    id: '1131',
    imgUrl: image.mineracao,
    curriculum: [
      {
        title: 'GERAIS',
        contents: [
          'Introdução a Administração',
          'Ecologia',
          'Cartografia',
          'Mineralogia',
          'Topografia e GeoProcessamento',
          'Introdução à Gestão Ambiental',
          'Princípios da Climatologia e Hidrologia',
          'Direito e legislação ambiental',
        ],
      },
      {
        title: 'Auxiliar de Supervisor de Turno de Mineração - CBO 7101-20',
        contents: [
          'Topografia de Minas',
          'Licenciamento Ambiental',
          'Geologia I',
          'Gestão de Obras',
          'Hidrogeologia',
          'Caracterização Tecnológica dos Minérios',
          'Depósito de Minerais',
        ],
      },
      {
        title:
          'Auxiliar de Supervisor de apoio operacional na mineração - CBO 7101-05',
        contents: [
          'Geologia II',
          'Avaliação de Impactos Ambientais I',
          'Geologia Estrutural',
          'Operações Mineiras',
          'Petrologia',
          'Prospecção geofísica e geoquímica',
          'Lavras de Minas a Céu Aberto',
          'Estabilidade de taludes e contenções',
          'Economia mineral e engenharia econômica',
        ],
      },
      {
        title: 'Auxiliar de Inspetor de Produção CBO - 7101-15',
        contents: [
          'Avaliação de Impactos Ambientais II',
          'Mecânica das Rochas',
          'Responsabilidade Socioambiental',
          'Recuperação de Áreas Degradadas',
          'Lavras de minas subterrâneas',
          'Tratamento de Minérios',
          'Ventilação e condicionamento de minas',
        ],
      },
      {
        title: 'Trabalho de Conclusão de Curso em Mineração',
        contents: ['Trabalho de Conclusão de Curso em Mineração'],
      },
    ],
  },
  {
    id: '3349',
    imgUrl: image.rh,
    curriculum: [
      {
        title: 'Auxiliar Administrativo – CBO 4110-05',
        contents: [
          'Introdução a Administração',
          'Cultura e Clima Organizacional',
          'Administração de Pessoal',
          'Teorias Aplicadas na Administração',
          'Matemática Financeira',
          'Relações Interpessoais',
          'Gestão de Pessoas I',
          'Modelos de Gestão',
          'Gestão do Conhecimento nas Organizações',
          'Rotinas de Pessoal',
        ],
      },
      {
        title: 'Auxiliar de Administrador de Recursos Humanos - CBO 2521-05',
        contents: [
          'Administração de Cargos, Salários e Benefícios',
          'Coaching e Carreira I',
          'Gestão de Pessoas II',
          'Recursos Humanos: Fundamentos e Processos',
          'Recrutamento e Seleção de Pessoas',
          'Treinamento e Desenvolvimento de Pessoas',
          'Direito do Trabalho',
        ],
      },
      {
        title: 'Auxiliar de Analista de Recursos Humanos - CBO 2524-05',
        contents: [
          'Coaching e Carreira II',
          'LGPD – Lei Geral de Proteção de Dados Pessoais',
          'Gestão de Remuneração e Benefícios em Cargos e Salários',
          'Avaliação do Desempenho das Pessoas',
          'Gestão Estratégica e Planejamento em RH',
          'Planejamento em Gestão de Pessoas',
        ],
      },
      {
        title: 'Trabalho de Conclusão de Curso em Recursos Humanos',
        contents: ['Trabalho de Conclusão de Curso em Recursos Humanos'],
      },
    ],
  },
  {
    id: '7285',
    imgUrl: image.redes,
    curriculum: [
      {
        title: 'Conteúdo detalhado do curso',
        contents: [
          'Fundamentos de redes de computadores - sg',
          'Arquitetura TCP/IP I – sg',
          'Cabeamento Estruturado I – sg',
          'Redes de Computadores – ies',
          'Infraestrutura de TI – sg',
          'Arquitetura e Organização de Computadores - sg',
          'Arquitetura de Servidores - sg',
          'Sistemas Operacionais - sg',
          'Comunicação de Dados - sg',
          'Arquitetura TCP/IP II - sg',
          'Redes sem Fio - sg',
          'Roteamento - sg',
          'Infraestrutura de Redes - sg',
          'Gerenciamento de redes de computadores -sg',
          'Cabeamento Estruturado II - sg',
          'Projeto Prático I',
          'Forense Computacional - sg',
          'Redes sem Fio e Comunicação Móvel I - sg',
          'Projeto de redes de computadores - sg',
          'Redes de Longa Distância - sg',
          'Segurança de redes de computadores - sg',
          'Sistemas Operacionais de Redes Abertas I - sg',
          'Integração de Aplicações - sg',
          'Programação em Ambientes de Redes de Computadores - sg',
          'Projeto Prático II',
          'Redes sem Fio e Comunicação Móvel II- sg',
          'Redes de alta disponibilidade - sg',
          'Redes Convergentes - sg',
          'Sistemas Operacionais de Redes Abertas II - sg',
          'Projeto e Desempenho de Redes - sg',
          'Qualidade e Desempenho de Redes - sg',
          'Projeto Prático III',
          'TRABALHO DE CONCLUSÃO DE CURSO',
        ],
      },
    ],
  },
  {
    id: '4810',
    imgUrl: image.secEscolar,
    videoUrl: 'BU9N9wTdcAE',
    curriculum: [
      {
        title: 'AUXILIAR DE AGENTE DE ORGANIZAÇÃO ESCOLAR – CBO – 3321-10',
        contents: [
          'História da Educação',
          'Fundamentos Econômicos da Educação',
          'Legislação Educacional',
          'Políticas Públicas em Educação',
          'Fundamentos Gerais da Educação',
          'Fundamentos Gerais da Educação Básica',
          'Fundamentos Teóricos e Metodológicos da Alfabetização',
          'Fundamentos Teóricos e Metodológicos da Educação Especial e Inclusiva',
          'Fundamentos Teóricos e Metodológicos da Educação Infantil',
          'Fundamentos Teóricos e Metodológicos da Inclusão',
          'Pratica em Sistema Escolar I',
        ],
      },
      {
        title: 'AUXILIAR DE COORDENADOR ESCOLAR – CBO 2394-05',
        contents: [
          'Fundamentos Metodológicos em EJA I',
          'Fundamentos Teóricos e Metodológicos Para a Educação em Tempo Integral',
          'Bases Históricas e Legais da Educação em Tempo Integral',
          'Cerimonial e Regras de Protocolos',
          'Comunicação Empresarial e Correspondência',
          'Gestão Escolar',
          'Gestão Educacional e Organização do Trabalho Pedagógico',
          'Gestão Educacional: Direção, Coordenação e Supervisão',
          'Princípios e Métodos de Supervisão e Orientação Educacional',
          'Ação Supervisora',
          'Teoria e Prática da Inspeção Escolar',
          'Avaliação Educacional',
          'Avaliação Institucional',
          'Pratica em Sistema Escolar II',
        ],
      },
      {
        title: 'AUXILIAR DE ORIENTAÇÃO ESCOLAR – CBO – 2394-05',
        contents: [
          'Dificuldades de Aprendizagem - dr',
          'Diversidade na Aprendizagem de Pessoas Com Necessidades Especiais - dr',
          'Cenários e Modalidades da Ead - dr',
          'Currículo Estruturado: Implementação de Programas Pedagógicos - dr',
          'Didática - dr',
          'Orientação Educacional - dr',
          'Pedagogia e Empreendedorismo - dr',
          'Pratica em Sistema Escolar III',
        ],
      },
      {
        title: 'TRABALHO DE CONCLUSÃO DE CURSO EM SECRETARIA ESCOLAR',
        contents: ['Trabalho de Conclusão de Curso em Secretaria Escolar'],
      },
    ],
  },
  {
    id: '4811',
    imgUrl: image.secretariado,
    videoUrl: 'aM1ZP_En_bI',
    curriculum: [
      {
        title: 'AUXILIAR ADMINISTRATIVO – CBO 4110-05',
        contents: [
          'Introdução à Administração',
          'Empreendedorismo',
          'Introdução ao Empreendedorismo',
          'Teorias Aplicadas na Administração',
          'Matemática Financeira',
          'Introdução à Matemática Financeira',
          'Gestão da Qualidade Total',
          'Modelos de Gestão',
          'Organização, Sistemas e Métodos',
          'Processos Gerenciais',
          'Atividades Complementares - Pacote Office',
          'Introdução ao Word',
          'Introdução ao Excel',
        ],
      },
      {
        title: 'AUXILIAR DE RECEPÇÃO - CBO 4221-05',
        contents: [
          'Fundamentos da Contabilidade',
          'Contabilidade para não Contadores',
          'Fundamentos da Língua Portuguesa',
          'Nivelamento de Português',
          'Comunicação Empresarial',
          'Administração Financeira',
          'Fundamentos da Economia',
          'Atividade Prática de Secretariado I',
        ],
      },
      {
        title: 'AUXILIAR DE SECRETARIA - CBO 4221-05',
        contents: [
          'Comunicação Interna',
          'Português',
          'Leitura e Interpretação de Textos',
          'Administração de Pessoal',
          'Administração de Micro e Pequenas Empresas',
          'Gestão do Desempenho Organizacional',
          'Sistemas de Informação para Gestão',
          'Análise de Mídias Sociais',
          'Atividade Prática de Secretariado II',
        ],
      },
      {
        title: 'Trabalho de Conclusão de Curso de Secretariado',
        contents: ['Trabalho de Conclusão de Curso de Secretariado'],
      },
    ],
  },
  {
    id: '24',
    imgUrl: image.segurancaTrab,
    videoUrl: 'FEcCYhWrFAY',
    curriculum: [
      {
        title: 'Auxiliar Técnico em Segurança do Trabalho - CBO 3615-05',
        contents: [
          'Introdução a Segurança do Trabalho',
          "Introdução às NR's de 01 a 12",
          "Introdução às NR's de 13 a 24",
          "Introdução às NR's de 25 a 37",
          'Legislação Aplicada',
          'Desenho Técnico',
          'Gestão de Pessoas',
          'Liderança',
          'Gestão da Qualidade Total',
        ],
      },
      {
        title: 'Auxiliar de Agente de Higiene e Segurança - CBO 2543-10',
        contents: [
          'Gerenciamento de Riscos',
          'Segurança em Eletricidade',
          'Segurança Logística',
          'NR 5 (CIPA) - Comissão Interna de Prevenção de Acidentes',
          'Prevenção e Combate a Incêndio',
          'Higiene e Segurança do Trabalho',
          'Técnicas de Análise de Riscos',
          'Trabalho Prático em Segurança do Trabalho I',
        ],
      },
      {
        title: 'Auxiliar de Segurança - CBO 2543-10',
        contents: [
          'Avaliação de Risco e Impactos Ambientais',
          'Gestão de Projetos de Prevenção',
          'Introdução ao Atendimento Pré-Hospitalar',
          'Estatística',
          'Ergonomia',
          'Segurança do Trabalho na Construção Civil',
          'Desenvolvimento e Interpretação de Textos',
        ],
      },
      {
        title: 'Auxiliar de Enfermagem do Trabalho - CBO - 3222-35',
        contents: [
          'Método Quantitativo e Qualitativo',
          'Amostragem',
          'Saúde, Segurança do Trabalho e Meio Ambiente',
          'Saúde Ocupacional',
          'Primeiros Socorros',
          'Avaliação do Desempenho das Pessoas',
          'Biossegurança',
          'Trabalho Prático em Segurança do Trabalho II',
        ],
      },
      {
        title: 'Trabalho de Conclusão de Curso TST',
        contents: ['Trabalho de Conclusão de Curso TST'],
      },
    ],
  },
  {
    id: '6313',
    imgUrl: image.publicos,
    videoUrl: 'hL9fyyHseEk',
    curriculum: [
      {
        title: 'AUXILIAR ADMINISTRATIVO – CBO 4110-05',
        contents: [
          'INTRODUÇÃO A ADMINISTRAÇÃO',
          'EMPREENDEDORISMO',
          'INTRODUÇÃO AO EMPREENDEDORISMO',
          'TEORIAS APLICADAS NA ADMINISTRAÇÃO',
          'MATEMÁTICA FINANCEIRA',
          'INTRODUÇÃO A MATEMÁTICA FINANCEIRA',
          'GESTÃO DA QUALIDADE TOTAL',
          'ORGANIZAÇÃO, SISTEMAS E MÉTODOS',
          'PROCESSOS GERENCIAIS',
        ],
      },
      {
        title: 'AUXILIAR DE GESTÃO PUBLICA - CBO 2521-05',
        contents: [
          'CONTROLADORIA PÚBLICA',
          'CONTROLES INTERNOS E EXTERNOS',
          'LICITAÇÕES E CONTRATOS I',
          'PLANEJAMENTO E ORÇAMENTO PÚBLICO I',
          'GESTÃO DE PESSOAS APLICADAS AO SETOR PÚBLICO',
          'GESTÃO DE INFORMAÇÕES NO SETOR PÚBLICO',
          'GESTÃO DE POLÍTICAS PÚBLICAS',
          'MARKETING PÚBLICO I',
          'AUDITORIA NO SETOR PÚBLICO',
          'GOVERNANÇA NA GESTÃO PÚBLICA',
        ],
      },
      {
        title: 'AUXILIAR DE PLANEJAMENTO E ORÇAMENTO - CBO 1115-10',
        contents: [
          'FISCALIZAÇÃO TRIBUTÁRIA: PRERROGATIVAS E LIMITES',
          'GESTÃO SOCIAL',
          'LICITAÇÕES E CONTRATOS II',
          'ELABORAÇÃO E IMPLEMENTAÇÃO DE POLÍTICAS PÚBLICAS',
          'MARKETING PÚBLICO II',
          'LEGISLAÇÃO PROCESSUAL APLICADA',
          'DIREITO PÚBLICO E PRIVADO',
          'AVALIAÇÃO NO SETOR PÚBLICO',
          'POLÍTICAS PÚBLICAS PARA O AGRONEGÓCIO',
          'PLANEJAMENTO E ORÇAMENTO PÚBLICO II',
        ],
      },
      {
        title: 'TRABALHO DE CONCLUSÃO DE CURSO - SERVIÇOS PÚBLICOS',
        contents: [],
      },
    ],
  },
  {
    id: '5376',
    imgUrl: image.transacoesImob,
    videoUrl: 'M0TaRVh39sU',
    curriculum: [
      {
        title: 'Auxiliar Administrativo – CBO 4110-05',
        contents: [
          'Introdução a Administração',
          'Empreendedorismo',
          'Introdução ao Empreendedorismo',
          'Teorias Aplicadas na Administração',
          'Matemática Financeira',
          'Introdução a Matemática Financeira',
          'Gestão da Qualidade Total',
          'Modelos de Gestão',
          'Organização, Sistemas e Métodos',
          'Processos Gerenciais',
        ],
      },
      {
        title: 'Auxiliar de Escritório Imobiliário – CBO 4110-05',
        contents: [
          'Introdução a Técnicas de Negociação',
          'Gestão de Vendas e Negociação',
          'Introdução a Teoria Geral dos Contratos',
          'Introdução ao Direito do Consumidor',
          'Administração de Imóveis e Locação',
          'Marketing Digital',
          'Análise de Mídias Sociais',
        ],
      },
      {
        title: 'Auxiliar de Avaliador de Imóveis CBO – 3544-10',
        contents: [
          'Mercado e Operações Imobiliárias',
          'Planejamento Urbano e Ambiental',
          'Estratégia de Marketing em Negócios Imobiliários',
        ],
      },
      {
        title: 'Avaliador de Imóveis CBO – 3544-10',
        contents: [
          'Tópicos Especiais',
          'Avaliação de Imóveis',
          'Direito Imobiliário',
        ],
      },
      {
        title: 'Estágio de TTI 200h (obrigatório)',
        contents: ['Estágio de TTI 200h (obrigatório)'],
      },
      {
        title: 'Trabalho de Conclusão de Curso de TTI',
        contents: ['Trabalho de Conclusão de Curso de TTI'],
      },
    ],
  },
  {
    id: '4812',
    imgUrl: image.vendas,
    videoUrl: 'mAnqklQTsJg',
    curriculum: [
      {
        title: 'Auxiliar Administrativo – CBO 4110-05',
        contents: [
          'Introdução à Administração',
          'Empreendedorismo',
          'Introdução ao Empreendedorismo',
          'Teorias Aplicadas na Administração',
          'Matemática Financeira',
          'Introdução à Matemática Financeira',
          'Gestão da Qualidade Total',
          'Modelos de Gestão',
          'Organização, Sistemas e Métodos',
          'Processos Gerenciais',
        ],
      },
      {
        title:
          'Qualificação Profissional Técnica de Nível Médio em Promotor de Vendas – CBO 3541-30',
        contents: [
          'Administração de Vendas',
          'Direito do Consumidor',
          'Comportamento do Consumidor',
          'Gestão de Relacionamento com o Cliente',
          'Análise e Planejamento Mercadológico',
          'Gestão do Composto Promocional',
          'Negociação e Vendas',
          'Administração de Marketing I',
        ],
      },
      {
        title:
          'Qualificação Profissional Técnica de Nível Médio Supervisor de Vendas - CBO 5201-10',
        contents: [
          'Administração de Vendas',
          'Análise de Cenários e Planejamento Mercadológico',
          'Gestão de Vendas e Negociação',
          'Custos e Formação de Preços',
          'Análise de Risco e de Crédito',
          'Pesquisa de Marketing',
          'Administração de Marketing II',
        ],
      },
      {
        title: 'Trabalho de Conclusão de Curso',
        contents: ['Trabalho de Conclusão de Curso'],
      },
    ],
  },
  {
    id: '3350',
    imgUrl: image.juridicos,
    curriculum: [
      {
        title: 'Gerais',
        contents: [
          'Noções gerais de direito',
          'Filosofia do direito',
          'Fundamentos de direito',
          'Hermenêutica jurídica',
          'Interpretação de textos',
          'Produção e interpretação de textos',
        ],
      },
      {
        title: 'Auxiliar de Assistente Jurídico - CBO 2410-05',
        contents: [
          'Teoria geral do processo',
          'Gestão de serviços jurídicos',
          'Responsabilidade civil I',
          'Instituições do processo civil',
          'Noções de direito do consumidor',
          'Instituições do processo administrativo e constitucional',
          'Registro de títulos e documentos',
          'Fundamentos de criminalística',
          'Direito tributário',
        ],
      },
      {
        title: 'Auxiliar de serviços jurídicos - CBO 3514-30',
        contents: [
          'Responsabilidade civil II',
          'Direito processual penal: procedimentos e recursos',
          'Registro civil de pessoas naturais e o registro empresarial',
          'Registro de imóveis e gestão patrimonial',
          'Registro de notas e protestos',
          'Direito digital',
          'Sistema registral e notarial brasileiro',
          'Direito do trabalho',
          'Direito comercial e do consumidor',
        ],
      },
      {
        title: 'Auxiliar de Assessor jurídico - CBO 2410-40',
        contents: [
          'Tecnologia da informação poder judiciário',
          'Teoria do processo judicial e extrajudicial',
          'Gestão de serviços extrajudiciais',
          'Direito e legislação ambiental',
          'Direito e legislação social',
          'Direito empresarial',
          'Direito imobiliário',
        ],
      },
      {
        title: 'Trabalho de Conclusão de Curso em Serviços Jurídicos',
        contents: [],
      },
    ],
  },
]
